### ISSUE TITLE
Could not find active fragment with index -1

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PretendYoureXyzzyAndroid#27]
```
java.lang.IllegalStateException: Could not find active fragment with index -1
       at androidx.fragment.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3076)
       at androidx.fragment.app.FragmentController.restoreAllState(FragmentController.java:158)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:344)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at com.gianlu.commonutils.NightlyActivity.onCreate(NightlyActivity.java:25)
       at com.gianlu.pretendyourexyzzy.MainActivity.onCreate(MainActivity.java:79)
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4621)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by murali129** [comment]
Hey any idea how did you fix this?

**Comment by devgianlu** [comment]
I ended up rewriting the entire code.

**Comment by joshallenit** [comment]
This can happen with a combination of [dismissAllowingStateLoss][1] after [onSaveInstanceState][1] and [retainInstanceState][2].

See [answer to "Could not find active fragment with index -1"][3]


  [1]: https://developer.android.com/reference/android/app/Fragment#onSaveInstanceState(android.os.Bundle)
  [2]: https://developer.android.com/reference/android/app/Fragment#setRetainInstance(boolean)
  [3]: https://stackoverflow.com/a/66119253/1596587
